import type { User, Listing, Offer, WalletEntry } from './types';

export const mockUsers: Record<string, User> = {
  'user-1': {
    uid: 'user-1',
    role: 'owner',
    displayName: 'Alex Johnson',
    email: 'alex.j@example.com',
    kycStatus: 'verified',
    trustScore: 95,
    vipTier: 'trailblazer',
    creditsBalance: 12500,
    clubMember: true,
    abuseFlags: { frozen: false, reason: null },
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: '2024-05-20T11:30:00Z',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
  'user-2': {
    uid: 'user-2',
    role: 'guest',
    displayName: 'Samantha Bee',
    email: 'sam.b@example.com',
    kycStatus: 'verified',
    trustScore: 88,
    vipTier: 'navigator',
    creditsBalance: 5000,
    clubMember: false,
    abuseFlags: { frozen: false, reason: null },
    createdAt: '2023-03-10T09:00:00Z',
    updatedAt: '2024-05-18T14:00:00Z',
    avatarUrl: 'https://placehold.co/100x100.png',
  },
};

export const mockListings: Listing[] = [
  {
    listingId: 'listing-1',
    ownerUid: 'user-1',
    resort: {
      id: 'resort-1',
      name: 'Maui Seaside Resort',
      brand: 'Hilton Grand Vacations',
      location: { country: 'USA', region: 'Hawaii', city: 'Maui' },
      tier: 'lux',
      imageUrl: 'https://placehold.co/600x400.png',
    },
    unit: {
      bedrooms: 2,
      sleeps: 6,
      features: { kitchen: true, view: 'ocean' },
    },
    stay: { startDate: '2024-07-12', endDate: '2024-07-19', nights: 7 },
    proof: { verified: true },
    source: 'owner',
    maintenanceFeeUSD: 1200,
    tradeValueScore: 85,
    creditValue: 6800,
    status: 'active',
    tradeModes: { creditsOnly: true, tradePlusCredits: true, tradeOnly: false },
    allowOffers: true,
    minOfferPct: 0.6,
    visibility: 'public',
    analytics: { views: 1204, offers: 15, saves: 45 },
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-05-15T11:30:00Z',
  },
  {
    listingId: 'listing-2',
    ownerUid: 'user-2',
    resort: {
      id: 'resort-2',
      name: 'Aspen Mountain Lodge',
      brand: 'Marriott Vacation Club',
      location: { country: 'USA', region: 'Colorado', city: 'Aspen' },
      tier: 'mid',
      imageUrl: 'https://placehold.co/600x400.png',
    },
    unit: {
      bedrooms: 1,
      sleeps: 4,
      features: { kitchen: true, view: 'resort' },
    },
    stay: { startDate: '2024-12-20', endDate: '2024-12-25', nights: 5 },
    proof: { verified: true },
    source: 'owner',
    maintenanceFeeUSD: 800,
    tradeValueScore: 78,
    creditValue: 6240,
    status: 'active',
    tradeModes: { creditsOnly: true, tradePlusCredits: true, tradeOnly: true },
    allowOffers: true,
    minOfferPct: 0.7,
    visibility: 'public',
    analytics: { views: 850, offers: 8, saves: 22 },
    createdAt: '2024-04-10T10:00:00Z',
    updatedAt: '2024-05-16T11:30:00Z',
  },
  {
    listingId: 'listing-3',
    ownerUid: 'user-1',
    resort: {
      id: 'resort-3',
      name: 'Orlando Sunshine Villas',
      brand: 'Wyndham',
      location: { country: 'USA', region: 'Florida', city: 'Orlando' },
      tier: 'value',
      imageUrl: 'https://placehold.co/600x400.png',
    },
    unit: {
      bedrooms: 3,
      sleeps: 8,
      features: { kitchen: true, view: 'garden' },
    },
    stay: { startDate: '2024-08-05', endDate: '2024-08-10', nights: 5 },
    proof: { verified: true },
    source: 'developer',
    maintenanceFeeUSD: 650,
    tradeValueScore: 72,
    creditValue: 5760,
    status: 'active',
    tradeModes: { creditsOnly: true, tradePlusCredits: false, tradeOnly: false },
    allowOffers: false,
    minOfferPct: 0.8,
    visibility: 'public',
    analytics: { views: 2100, offers: 0, saves: 112 },
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-05-18T11:30:00Z',
  },
  {
    listingId: 'listing-4',
    ownerUid: 'user-2',
    resort: {
      id: 'resort-4',
      name: 'Cancun Beach Palace',
      brand: 'Palace Resorts',
      location: { country: 'Mexico', region: 'Quintana Roo', city: 'Cancun' },
      tier: 'lux',
      imageUrl: 'https://placehold.co/600x400.png',
    },
    unit: {
      bedrooms: 1,
      sleeps: 2,
      features: { kitchen: false, view: 'ocean' },
    },
    stay: { startDate: '2024-11-10', endDate: '2024-11-15', nights: 5 },
    proof: { verified: true },
    source: 'owner',
    maintenanceFeeUSD: 950,
    tradeValueScore: 92,
    creditValue: 7360,
    status: 'under_offer',
    tradeModes: { creditsOnly: true, tradePlusCredits: true, tradeOnly: true },
    allowOffers: true,
    minOfferPct: 0.65,
    visibility: 'public',
    analytics: { views: 3500, offers: 25, saves: 98 },
    createdAt: '2024-05-05T10:00:00Z',
    updatedAt: '2024-05-19T11:30:00Z',
  },
];

export const mockOffers: Offer[] = [
  {
    offerId: 'offer-1',
    listingId: 'listing-1', // Maui Seaside Resort
    fromUid: 'user-2', // Samantha
    toUid: 'user-1', // Alex
    offeredListingId: null,
    offeredCredits: 6500,
    aiRank: 'fair',
    status: 'pending',
    expiresAt: '2024-06-01T10:00:00Z',
    createdAt: '2024-05-20T10:00:00Z',
    updatedAt: '2024-05-20T10:00:00Z',
  },
  {
    offerId: 'offer-2',
    listingId: 'listing-4', // Cancun Beach Palace
    fromUid: 'user-1', // Alex
    toUid: 'user-2', // Samantha
    offeredListingId: 'listing-2', // Aspen Mountain Lodge
    offeredCredits: 1000,
    aiRank: 'great',
    status: 'pending',
    expiresAt: '2024-05-28T10:00:00Z',
    createdAt: '2024-05-19T12:00:00Z',
    updatedAt: '2024-05-19T12:00:00Z',
  },
  {
    offerId: 'offer-3',
    listingId: 'listing-2',
    fromUid: 'user-1',
    toUid: 'user-2',
    offeredListingId: null,
    offeredCredits: 4000,
    aiRank: 'low',
    status: 'declined',
    expiresAt: '2024-05-22T10:00:00Z',
    createdAt: '2024-05-15T10:00:00Z',
    updatedAt: '2024-05-16T10:00:00Z',
  },
];

export const mockWalletEntries: WalletEntry[] = [
  {
    entryId: 'w-1',
    type: 'purchase',
    amount: 10000,
    refType: 'order',
    refId: 'order-1',
    createdAt: '2024-05-01T12:00:00Z',
    signed: true,
    description: 'Credit Purchase',
  },
  {
    entryId: 'w-2',
    type: 'deposit_earn',
    amount: 6800,
    refType: 'listing',
    refId: 'listing-1',
    createdAt: '2024-05-02T14:00:00Z',
    signed: true,
    description: 'Deposit: Maui Seaside Resort',
  },
  {
    entryId: 'w-4',
    type: 'vip_reward',
    amount: 500,
    refType: 'admin',
    refId: 'admin-reward-may',
    createdAt: '2024-05-10T09:00:00Z',
    signed: true,
    description: 'Trailblazer Monthly Reward',
  },
];
